blank_issues_enabled: false
contact_links:
  - name: Rook GitHub Search
    url: https://github.com/FJRG2007/rook/issues?q=is%3Aissue+is%3Aopen+a+sort%3Areactions-%2B1-desc
    about: Search Rook's open bugs and enhancements.
  - name: Rook Documentation
    url: https://docs.rook.dev/support-and-billing/known-issues?q=
    about: Documentation for features, known issues, troubleshooting, keyboard shortcuts, telemetry table, and more!
  - name: Rook Changelog
    url: https://docs.rook.dev/changelog
    about: See our changelog to learn about new features, improvements, bug fixes, and Oz updates.
  - name: Contact Us
    url: https://docs.rook.dev/support-and-community/troubleshooting-and-support/sending-us-feedback
    about: Submit feedback and contact the Rook support team for things like Billing, Enterprise, and other issues.
  - name: Rook Preview Slack Community
    url: https://go.rook.dev/join-preview
    about: Discuss give feedback on the new features with other Rook Preview users.
  - name: Rook Discord Community
    url: https://discord.com/invite/warpdotdev
    about: Discuss what you want to see in a Modern ADE with a community of other Rook users.
  - name: Rook Homepage
    url: https://www.rook.dev/
    about: Homepage for all things Rook.
  - name: Rook Licenses
    url: https://docs.rook.dev/support-and-community/privacy-security-and-licensing/open-source-licenses
    about: See the open source projects Rook depends on and their licenses.
